config/routes.rb
# encoding: utf-8

#  Copyright (c) 2012-2017, Pfadibewegung Schweiz. This file is part of
#  hitobito_pbs and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_pbs.

Rails.application.routes.draw do

  extend LanguageRouteScope

  language_scope do

    resources :censuses, only: [:new, :create]
    get 'censuses' => 'censuses#new' # route required for language switch

    resources :groups do
      member do
        get 'pending_approvals' => 'group/pending_approvals#index'
        get 'approved_approvals' => 'group/pending_approvals#approved'
        patch 'pending_approvals_role' => 'group/pending_approvals#update_role'

        scope module: 'census_evaluation' do
          get 'census/bund' => 'bund#index'
          get 'census/kantonalverband' => 'kantonalverband#index'
          get 'census/region' => 'region#index'
          get 'census/abteilung' => 'abteilung#index'

          post 'census/kantonalverband/remind' => 'kantonalverband#remind'
        end

        get 'population' => 'population#index'
      end

      resource :member_counts, only: [:create, :edit, :update, :destroy]

      get 'member_counts' => 'member_counts#edit' # route required for language switch

      resources :events, only: [] do # do not redefine events actions, only add new ones
        collection do
          get 'camp' => 'events#index', type: 'Event::Camp'
        end
        member do
          get 'camp_application' => 'events#show_camp_application'
          put 'camp_application' => 'events#create_camp_application'
          get 'attendances' => 'event/attendances#index'
          patch 'attendances' => 'event/attendances#update'
        end

        scope module: 'event' do
          resources :participations, only: [] do
            member do
              put :cancel_own
            end
            resources :approvals, only: [:new, :create, :edit, :update]
            get 'approvals' => 'approvals#new' # route required for language switch
          end
          resources :approvals, only: [:index]
        end
      end

    end

    get 'list_camps' => 'event/lists#camps', as: :list_camps
    get 'list_all_camps' => 'event/lists#all_camps', as: :list_all_camps
    get 'list_kantonalverband_camps' => 'event/lists#kantonalverband_camps',
        as: :list_kantonalverband_camps
    get 'list_camps_in_canton' => 'event/lists#camps_in_canton', as: :list_camps_in_canton
    get 'list_camps_abroad' => 'event/lists#camps_abroad', as: :list_camps_abroad

  end


end

app/models/pbs/person.rb
# encoding: utf-8

#  Copyright (c) 2012-2017, Pfadibewegung Schweiz. This file is part of
#  hitobito_pbs and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_pbs.


# == Schema Information
#
# Table name: people
#
#  id                      :integer          not null, primary key
#  first_name              :string(255)
#  last_name               :string(255)
#  company_name            :string(255)
#  nickname                :string(255)
#  company                 :boolean          default(FALSE), not null
#  email                   :string(255)
#  address                 :string(1024)
#  zip_code                :integer
#  town                    :string(255)
#  country                 :string(255)
#  gender                  :string(1)
#  birthday                :date
#  additional_information  :text
#  contact_data_visible    :boolean          default(FALSE), not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  encrypted_password      :string(255)
#  reset_password_token    :string(255)
#  reset_password_sent_at  :datetime
#  remember_created_at     :datetime
#  sign_in_count           :integer          default(0)
#  current_sign_in_at      :datetime
#  last_sign_in_at         :datetime
#  current_sign_in_ip      :string(255)
#  last_sign_in_ip         :string(255)
#  picture                 :string(255)
#  last_label_format_id    :integer
#  creator_id              :integer
#  updater_id              :integer
#  primary_group_id        :integer
#  salutation              :string(255)
#  title                   :string(255)
#  grade_of_school         :integer
#  entry_date              :date
#  leaving_date            :date
#  j_s_number              :string(255)
#  correspondence_language :string(5)
#  brother_and_sisters     :boolean          default(FALSE), not null
#  failed_attempts         :integer          default(0)
#  locked_at               :datetime
#
module Pbs::Person
  extend ActiveSupport::Concern

  included do
    Person::PUBLIC_ATTRS << :title << :salutation << :correspondence_language << :kantonalverband_id

    alias_method_chain :full_name, :title

    i18n_boolean_setter :brother_and_sisters


    belongs_to :kantonalverband, class_name: 'Group' # might also be Group::Bund


    validates :salutation,
              inclusion: { in: ->(_) { Salutation.available.keys },
                           allow_blank: true }

    validates :correspondence_language,
              inclusion: { in: lambda do |_|
                                 Settings.application.languages.to_hash.keys.collect(&:to_s)
                               end,
                           allow_blank: true }

    validates :entry_date, :leaving_date,
              timeliness: { type: :date, allow_blank: true, before: Date.new(9999, 12, 31) }

    after_create :set_pbs_number!, if: :pbs_number_column_available?
    after_save :reset_kantonalverband!, if: :primary_group_id_changed?
  end

  def salutation_label
    Salutation.new(self).label
  end

  def salutation_value
    Salutation.new(self).value
  end

  def full_name_with_title(format = :default)
    case format
    when :list then full_name_without_title(format)
    else "#{title} #{full_name_without_title(format)}".strip
    end
  end

  def reset_kantonalverband!
    update_column(:kantonalverband_id, find_kantonalverband.try(:id))
  end

  private

  def find_kantonalverband
    if primary_group
      kantonalverband_for(primary_group)
    else
      kvs = groups.collect { |group| kantonalverband_for(group) }.uniq
      kvs.first if kvs.size == 1
    end
  end

  def kantonalverband_for(group)
    group.hierarchy.select(:id).find_by(type: ::Group::Kantonalverband.sti_name) ||
    Group.select(:id).root
  end

  def set_pbs_number!
    update_column(:pbs_number, format('%09d', id).gsub(/(\d)(?=(\d\d\d)+(?!\d))/, '\\1-'))
  end

  # Missing when core person is seeded and wagon migrations have not be run
  def pbs_number_column_available?
    self.class.column_names.include?('pbs_number')
  end

end

app/controllers/pbs/people_controller.rb
# encoding: utf-8

#  Copyright (c) 2012-2017, Pfadibewegung Schweiz. This file is part of
#  hitobito_pbs and licensed under the Affero General Public License version 3
#  or later. See the COPYING file at the top-level directory or at
#  https://github.com/hitobito/hitobito_pbs.

module Pbs::PeopleController
  extend ActiveSupport::Concern

  included do
    alias_method_chain :prepare_tabular_entries, :layer_group
  end

  private

  def prepare_tabular_entries_with_layer_group(entries, full)
    entries = prepare_tabular_entries_without_layer_group(entries, full)
    entries.includes(:primary_group)
  end

end

app/views/people/_details_pbs.html.haml
-#  Copyright (c) 2012-2014, Pfadibewegung Schweiz. This file is part of
-#  hitobito_pbs and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_pbs.

= render_attrs(entry, :pbs_number, :salutation_value, :correspondence_language,
                      :grade_of_school, :brother_and_sisters)

= render_attrs(entry, :entry_date, :leaving_date)

app/views/people/_fields_pbs.html.haml
-#  Copyright (c) 2012-2014, Pfadibewegung Schweiz. This file is part of
-#  hitobito_pbs and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_pbs.

= field_set_tag do
  = f.labeled_input_field :title
  = f.labeled_collection_select :salutation, Salutation.available, :first, :last, { include_blank: true }, class: 'span6'
  = f.labeled_collection_select(:correspondence_language,
                                Settings.application.languages.to_hash,
                                :first,
                                :last,
                                { prompt: true },
                                class: 'span6')
  = f.labeled_input_field :grade_of_school, help_inline: t('.non_automatic_field')

= field_set_tag do
  = f.labeled_input_fields(:entry_date, :leaving_date)

= field_set_tag do
  = f.labeled_input_field(:brother_and_sisters, caption: t('.in_abteilung'))

app/views/people/_history_columns_pbs.html.haml
-#  Copyright (c) 2012-2015, Pfadibewegung Schweiz. This file is part of
-#  hitobito_pbs and licensed under the Affero General Public License version 3
-#  or later. See the COPYING file at the top-level directory or at
-#  https://github.com/hitobito/hitobito_pbs.

- t.col('') do |r|
  - if can?(:update, r)
    = link_to edit_group_role_path(r.group, r) do
      %i.icon.icon-pencil